# curl --location --request POST 'localhost:8097/api/users/register'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "mobile":"18800277236",
#    "username":"zhangSan",
#    "password":"admin123"
#}'
POST localhost:8097/api/users/register
Content-Type: application/json

{
  "mobile": "18800277236",
  "username": "zhangSan",
  "password": "admin123"
}

###

GRPC localhost:50052/shop.shop.v1.Shop/Register
Content-Type: application/json

{
  "mobile": "18800277236",
  "username": "zhangSan",
  "password": "admin123"
}

###



# goods
#
###
GRPC localhost:50053/goods.v1.Goods/CreateCategory
Content-Type:application/json

{
  "name": "华为",
  "parentCategory": 1,
  "level": 1,
  "isTab": true,
  "sort": 1
}
###






###
GRPC localhost:50053/goods.v1.Goods/CreateGoodsType
Content-Type:application/json

{
  "id": 20,
  "name": "手机",
  "typeCode": "100000",
  "nameAlias": "手机通讯",
  "isVirtual": true,
  "desc": "手机通讯",
  "sort": 1
}

###
GRPC localhost:50053/goods.v1.Goods/CreateGoodsSpecification
Content-Type:application/json

{
  "typeId": 1,
  "name": "颜色",
  "sort": 1,
  "status": true,
  "isSku": true,
  "isSelect": true,
  "specificationValue": [
    {
      "value": "亮黑色",
      "sort": 1
    },
    {
      "value": "釉白色",
      "sort": 2
    }
  ]
}


###
GRPC localhost:50053/goods.v1.Goods/CreateAttrGroup
Content-Type:application/json

{
  "typeId": 1,
  "title": "主体",
  "desc": "商品主体信息",
  "status": true,
  "sort": 1
}


###
GRPC localhost:50053/goods.v1.Goods/CreateAttrValue
Content-Type:application/json

{
  "typeId": 1,
  "groupId": 1,
  "title": "上市年份",
  "desc": "上市年份",
  "status": true,
  "sort": 1,
  "attrValue": [
    {
      "groupId": 1,
      "value": "2021年"
    }
  ]
}