# curl --location --request POST 'localhost:8097/api/users/register'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "mobile":"18800277236",
#    "username":"zhangSan",
#    "password":"admin123"
#}'
POST localhost:8097/api/users/register
Content-Type: application/json

{
  "mobile": "18800277236",
  "username": "zhangSan",
  "password": "admin123"
}

###

GRPC localhost:50052/shop.shop.v1.Shop/Register
Content-Type: application/json

{
  "mobile": "18800277236",
  "username": "zhangSan",
  "password": "admin123"
}

###



# goods
#
###
GRPC localhost:50053/goods.v1.Goods/CreateCategory
Content-Type:application/json

{
  "name": "华为",
  "parentCategory": 1,
  "level": 1,
  "isTab": true,
  "sort": 1
}
###






###
GRPC localhost:50053/goods.v1.Goods/CreateGoodsType
Content-Type:application/json

{
  "id": 20,
  "name": "手机",
  "typeCode": "100000",
  "nameAlias": "手机通讯",
  "isVirtual": true,
  "desc": "手机通讯",
  "sort": 1
}

